// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "694856b0-1469-4f73-8c6a-efd7537140b1";

const char SSID[]               = "bofadn2";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "zya0@0jMLUDR1v#dHQox27nsc";    // Secret device password

void onMessengerChange();
void onPwnChange();
void onUmiditateChange();
void onLedChange();
void onTemperaturaChange();

String messenger;
int pwn;
CloudRelativeHumidity umiditate;
bool led;
CloudTemperature temperatura;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(messenger, READWRITE, ON_CHANGE, onMessengerChange);
  ArduinoCloud.addProperty(pwn, READWRITE, ON_CHANGE, onPwnChange);
  ArduinoCloud.addProperty(umiditate, READWRITE, ON_CHANGE, onUmiditateChange);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(temperatura, READWRITE, ON_CHANGE, onTemperaturaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
